attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.2960659121982872
embedding_labels: {}
embedding_paddings:
- month
- week
- day
embedding_sizes: {}
hidden_continuous_size: 22
hidden_continuous_sizes: {}
hidden_size: 36
learning_rate: 0.0010322318420096076
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 168
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  groups:
  - month
  method: robust
  method_kwargs: {}
  missing_:
    center: 81.38499999999999
    scale: 20.1659765625
  norm_: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 2
            - 13
          - !!python/object/apply:numpy.dtype
            args:
            - f8
            - false
            - true
            state: !!python/tuple
            - 3
            - <
            - null
            - null
            - null
            - -1
            - -1
            - 0
          - false
          - !!binary |
            mpmZmZnhV0BwPQrXo1hUQBSuR+F6XFdApHA9CtejV0D2KFyPwp1YQOxRuB6Fm1pApHA9CteTWECF
            61G4Hv1RQOxRuB6Fw1JAzczMzMz8UkAAAAAAAABFQAATPuqrphFAB/on5ApF6b+QwvUonFc0QML1
            KFzPAjVAyPUoXA+TKUAM16NwvQotQLgeheuRwDFA2KNwPUrHMEAfhetR2GJAQNejcD0qg0NACtej
            cH0qNED2KFyPAj4xQM2+BbX57jhACPhqB8bPMUC0uxjTFPc0QA==
        - !!python/object/apply:builtins.slice
          - 0
          - 2
          - 1
        - 2
    - - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.base.Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
            - !!python/object/apply:numpy.dtype
              args:
              - O8
              - false
              - true
              state: !!python/tuple
              - 3
              - '|'
              - null
              - null
              - null
              - -1
              - -1
              - 63
            - false
            - - center
              - scale
          name: null
      - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.numeric.Int64Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 13
            - !!python/object/apply:numpy.dtype
              args:
              - i8
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAI
              AAAAAAAAAAkAAAAAAAAACgAAAAAAAAALAAAAAAAAAAwAAAAAAAAADQAAAAAAAAA=
          name: month
    _typ: dataframe
    attrs: {}
  scale_by_group: false
  transformation: softplus
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
- precio_spot_center
- precio_spot_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- fechaHora
- demanda
- co2
- precio_gas
- prod_eolica
- prod_solar
- demanda_residual
- rampa
- month
- week
- day
- hour
- time_idx
- relative_time_idx
- precio_spot_lagged_by_24
- precio_spot_lagged_by_48
- precio_spot_lagged_by_72
time_varying_reals_encoder:
- fechaHora
- demanda
- co2
- precio_gas
- prod_eolica
- prod_solar
- demanda_residual
- rampa
- month
- week
- day
- hour
- time_idx
- relative_time_idx
- precio_spot_lagged_by_24
- precio_spot_lagged_by_48
- precio_spot_lagged_by_72
- precio_spot
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- precio_spot_center
- precio_spot_scale
- fechaHora
- demanda
- co2
- precio_gas
- prod_eolica
- prod_solar
- demanda_residual
- rampa
- month
- week
- day
- hour
- time_idx
- relative_time_idx
- precio_spot_lagged_by_24
- precio_spot_lagged_by_48
- precio_spot_lagged_by_72
- precio_spot
