attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels: {}
embedding_paddings:
- month
- week
- day
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 8
learning_rate: 0.001
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 144
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  groups:
  - week
  method: robust
  method_kwargs: {}
  missing_:
    center: 85.02250000000001
    scale: 17.0991015625
  norm_: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 2
            - 54
          - !!python/object/apply:numpy.dtype
            args:
            - f8
            - false
            - true
            state: !!python/tuple
            - 3
            - <
            - null
            - null
            - null
            - -1
            - -1
            - 0
          - false
          - !!binary |
            HoXrUbh2WEAzMzMzM5NWQBSuR+F6HFZAcT0K16PgSEAUrkfheuRTQAAAAAAAwFVAKVyPwvVYVUAK
            16NwPVpYQNejcD0K51pAXI/C9Sg8WECQwvUoXPdaQJqZmZmZsVhAZmZmZmaGVkAAAAAAAMhXQHE9
            CtejAFRAexSuR+G6V0AzMzMzM+tYQJqZmZmZGV5A9ihcj8IlWUAfhetRuA5YQOxRuB6FE1xAzczM
            zMwEWEAK16NwPbpdQFK4HoXrkVtAAAAAAABAX0DsUbgehbtXQM3MzMzM/FJAkQ+Z7jUlEUAAAAAA
            AIhRQFK4HoXrKVVAUrgehesxSkAfhetRuF5ZQML1KFyPElZAH4XrUbieTkAUrkfheqxRQHA9Ctej
            gFVAKs+ML3D9KUCuR+F6FH5LQPYoXI/CnVhApHA9CtcrUkBSuB6F65lQQHoUrkfhilFA7FG4HoXr
            TECF61G4HtVJQDMzMzMzc0FAULQTsF5ECUBsclNNJNoPQB+F61G4fjRAXI/C9SisQUBxnTVDxyPQ
            v8T88Pw1stu/Ek8rb5YFQsAEbNYqnfj1P56qKs4kk+E/NDMzM3NzM0DiehSuh/ExQOB6FK6HwTBA
            2KNwPUpfNkCicD0KVzQvQDwK16Pw3SNATOF6FC7YI0CkcD0KV7QkQM7MzMwMFTBAaGZmZub2LEDY
            o3A9SncxQEzhehQuuCdAXI/C9ahcKEDgehSux+EpQLBH4XqUzi5AZmZmZqZOMUBkZmZm5iYvQLge
            heuRIDBA7FG4HgXcLUCkcD0KF+QwQNijcD2KVytAwvUoXM96MUByPQrX4wAyQIbrUbheXTJAiOtR
            uJ51LkDXo3A9KvdDQB6F61H4Hj5AIVaphs+PJUDC9ShcrwpAQGZmZmaGbkFAHoXrUfiOO0AghetR
            OI8nQFK4HoUrijZAXI/C9WgEMkDOzMzMDLUxQDAzMzOzsy9AURtiibbUPkCPwvUonAc0QGhmZmbm
            ZihA9ChcjwLmM0DiehSuxwEtQJLC9SjcDyxA7FG4HgXcLkC4HoXr0RgnQDhT0ZoCfjFApvC9KEz9
            DEA7hA3KZG0fQO+Xh2oWKzVAC9ejcH2aM0BXiixaHJozQDYiw5fGoDNAjcXu9wTjM0BoUhMchQU1
            QDYiw5fGoDNA
        - !!python/object/apply:builtins.slice
          - 0
          - 2
          - 1
        - 2
    - - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.base.Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
            - !!python/object/apply:numpy.dtype
              args:
              - O8
              - false
              - true
              state: !!python/tuple
              - 3
              - '|'
              - null
              - null
              - null
              - -1
              - -1
              - 63
            - false
            - - center
              - scale
          name: null
      - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.numeric.Int64Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id001
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 54
            - !!python/object/apply:numpy.dtype
              args:
              - i8
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAI
              AAAAAAAAAAkAAAAAAAAACgAAAAAAAAALAAAAAAAAAAwAAAAAAAAADQAAAAAAAAAOAAAAAAAAAA8A
              AAAAAAAAEAAAAAAAAAARAAAAAAAAABIAAAAAAAAAEwAAAAAAAAAUAAAAAAAAABUAAAAAAAAAFgAA
              AAAAAAAXAAAAAAAAABgAAAAAAAAAGQAAAAAAAAAaAAAAAAAAABsAAAAAAAAAHAAAAAAAAAAdAAAA
              AAAAAB4AAAAAAAAAHwAAAAAAAAAgAAAAAAAAACEAAAAAAAAAIgAAAAAAAAAjAAAAAAAAACQAAAAA
              AAAAJQAAAAAAAAAmAAAAAAAAACcAAAAAAAAAKAAAAAAAAAApAAAAAAAAACoAAAAAAAAAKwAAAAAA
              AAAsAAAAAAAAAC0AAAAAAAAALgAAAAAAAAAvAAAAAAAAADAAAAAAAAAAMQAAAAAAAAAyAAAAAAAA
              ADMAAAAAAAAANAAAAAAAAAA1AAAAAAAAADYAAAAAAAAA
          name: week
    _typ: dataframe
    attrs: {}
  scale_by_group: false
  transformation: softplus
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
- precio_spot_center
- precio_spot_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- fechaHora
- demanda
- co2
- precio_gas
- prod_eolica
- prod_solar
- demanda_residual
- rampa
- month
- week
- day
- hour
- time_idx
- relative_time_idx
- precio_spot_lagged_by_24
- precio_spot_lagged_by_48
- precio_spot_lagged_by_72
time_varying_reals_encoder:
- fechaHora
- demanda
- co2
- precio_gas
- prod_eolica
- prod_solar
- demanda_residual
- rampa
- month
- week
- day
- hour
- time_idx
- relative_time_idx
- precio_spot_lagged_by_24
- precio_spot_lagged_by_48
- precio_spot_lagged_by_72
- precio_spot
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- precio_spot_center
- precio_spot_scale
- fechaHora
- demanda
- co2
- precio_gas
- prod_eolica
- prod_solar
- demanda_residual
- rampa
- month
- week
- day
- hour
- time_idx
- relative_time_idx
- precio_spot_lagged_by_24
- precio_spot_lagged_by_48
- precio_spot_lagged_by_72
- precio_spot
